shinyUI(fluidPage(
  titlePanel("Gompertz Calculator"),
  fluidRow(
    column(3,
           h3("Time Points"),
           numericInput("t1", label="", value=""),
           numericInput("t2", label="", value=""),
           numericInput("t3", label="", value=""),
           numericInput("t4", label="", value=""),
           numericInput("t5", label="", value=""),
           numericInput("t6", label="", value=""),
           numericInput("t7", label="", value=""),
           numericInput("t8", label="", value=""),
           numericInput("t9", label="", value=""),
           numericInput("t10", label="", value="")),
    column(3, 
           h3("Growth"),
           numericInput("e1", label="", value=""),
           numericInput("e2", label="", value=""),
           numericInput("e3", label="", value=""),
           numericInput("e4", label="", value=""),
           numericInput("e5", label="", value=""),
           numericInput("e6", label="", value=""),
           numericInput("e7", label="", value=""),
           numericInput("e8", label="", value=""),
           numericInput("e9", label="", value=""),
           numericInput("e10", label="", value=""),
           actionButton("action", label="Run")),
    column(6, 
         h3("Results"),
         plotOutput("uiResults")
))))
